### ISSUE TITLE
Example with getServerSideProps

### ISSUE THREAD

**Issue by ccannell** [markdoc/next.js#1]
Could you provide an example using getServerSideProps to get data that is then used in a Markdoc page? Thank you.

**Comment by mfix-stripe** [comment]
Sure thing! In your `next.config.js`, update the config to be:

```js
const withMarkdoc = require('@markdoc/next.js');

module.exports = withMarkdoc({ mode: 'server' })({
  pageExtensions: ['js', 'md', 'mdoc']
});
```

`mode: 'server'` being the operative change.

**Comment by ccannell** [comment]
I saw that in the documentation. I was hoping for help on where the `getServerSideProps` function goes and how it gets wired into the *.md documents. I have started with the [nextjs starter repo](https://github.com/markdoc/docs/tree/main/examples/simple-nextjs)
